# Write your MySQL query statement below
SELECT name FROM (
SELECT E1.NAME,COUNT(E2.MANAGERID) AS COUNT1
FROM EMPLOYEE E1 
JOIN EMPLOYEE E2
ON E1.ID = E2.MANAGERID
GROUP BY E1.NAME,e2.managerID) AS CHECK1
WHERE COUNT1>=5;

